FROM python:3.8
MAINTAINER wangrongxiang

ENV PYTHONPATH /usr/local/lib/python3.8/site-packages/:/root/dev/source-code/seahub/thirdpart:$PYTHONPATH
ENV CCNET_CONF_DIR ~/dev/conf
ENV SEAFILE_CONF_DIR ~/dev/seafile-data
ENV SEAFILE_CENTRAL_CONF_DIR ~/dev/conf

WORKDIR ~/dev/source-code/seahub
COPY . ./
COPY ./conf ~/dev

RUN pip install -r requirements.txt

ENTRYPOINTS ["python" "manage.py"]