FROM python:3.8
MAINTAINER wangrongxiang

ENV PYTHONPATH /usr/local/lib/python3.8/site-packages/:/root/dev/source-code/seahub/thirdpart:$PYTHONPATH
ENV CCNET_CONF_DIR /root/dev/conf
ENV SEAFILE_CONF_DIR /root/dev/seafile-data
ENV SEAFILE_CENTRAL_CONF_DIR /root/dev/conf

WORKDIR /root/dev/source-code/seahub
COPY . ./
COPY ./config_files /root/dev

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y build-essential python3-dev libldap2-dev libsasl2-dev slapd ldap-utils tox lcov valgrind && \
    pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 8082

ENTRYPOINT ["python", "manage.py", "runserver", "server:8000"]